services:
  - type: web
    name: blockestate-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blockestate-db
          property: connectionString
      - key: TOKEN_PASS
        generateValue: true
      - key: PORT
        value: 3000

databases:
  - name: blockestate-db
    plan: free
    databaseName: blockestate
    user: blockestate_user
